server:
  port: ":8080"

# 1. 中心化定义所有可用的限流规则
#    这里是规则的 "蓝图" 或 "模板"
rate_limiting:
  rules:
    # 规则1: 这是从您旧配置的 "default_token_bucket" 转换而来的
    - name: "default-ip-limit"
      type: "memory_token_bucket" # 指定使用的限流算法
      tokenBucket:
        capacity: 100   # 桶容量
        refillRate: 50  # 每秒填充速率 (tokens/sec)

    # 规则2: 这是为 /auth 路径定制的更严格的规则
    - name: "auth-service-limit"
      type: "memory_token_bucket"
      tokenBucket:
        capacity: 50
        refillRate: 20

    # 规则3: 这是为 /service-a 定制的、基于路径的宽松规则
    - name: "service-a-path-limit"
      type: "memory_token_bucket"
      tokenBucket:
        capacity: 200
        refillRate: 100

services:
  - name: "auth-service"
    instances:
      - url: "http://localhost:8085"
        weight: 1
      - url: "http://localhost:8086"
        weight: 1
    health_check_path: "/healthz"
    load_balancer: "round_robin"
  - name: "service-a"
    instances:
      - url: "http://localhost:8081"
        weight: 1
      - url: "http://localhost:8082"
        weight: 1
    health_check_path: "/healthz"
    load_balancer: "weighted_round_robin"
  - name: "service-b"
    instances:
      - url: "http://localhost:8083"
        weight: 1
      - url: "http://localhost:8084"
        weight: 1
    health_check_path: "/healthz"
    load_balancer: "least_connections"

# 2. 在每个路由中，通过插件按名称 "引用" 规则
routes:
  - path_prefix: "/auth"
    service_name: "auth-service"
    auth_required: false
    plugins:
      - name: "rateLimit"                # 插件名称，必须与代码中的常量匹配
        rule: "auth-service-limit"      # 引用上面定义的规则名称
        strategy: "ip"                  # 指定应用此规则的策略（按IP）

  - path_prefix: "/service-a"
    service_name: "service-a"
    auth_required: false
    plugins:
      - name: "rateLimit"
        rule: "service-a-path-limit"    # 引用上面定义的规则名称
        strategy: "path"                # 指定应用此规则的策略（按Path）

  - path_prefix: "/service-b"
    service_name: "service-b"
    auth_required: true
    plugins:
      - name: "rateLimit"
        rule: "default-ip-limit"        # 此路由应用默认的IP限流规则
        strategy: "ip"

jwt:
  secret_key: "your-very-secret-key-that-is-long-enough"
  duration_minutes: 60
