# file: configs/config.yaml
server:
  port: ":8080" # 网关的端口

services:
  - name: "auth-service"
    url: "http://localhost:8083"
    healthCheckPath: "/healthz" # 假设认证服务也有健康检查
  - name: "service-a"
    url: "http://localhost:8081"
    healthCheckPath: "/healthz" # 假设 service-a 的健康检查端点
  - name: "service-b"
    url: "http://localhost:8082"
    healthCheckPath: "/healthz" # 假设 service-b 的健康检查端点

routes:
  # 访问 /auth 开头的路径，转发给 auth-service，并且不需要 JWT 验证
  - path_prefix: "/auth"
    service_name: "auth-service"
    auth_required: false
  # 访问 /service-a 开头的路径，转发给 service-a，并且必须进行 JWT 验证
  - path_prefix: "/service-a"
    service_name: "service-a"
    auth_required: false
  # 示例：你也可以添加 service-b 的路由
  - path_prefix: "/service-b"
    service_name: "service-b"
    auth_required: true

jwt:
  # 这个密钥必须和认证服务里的完全一样
  secret_key: "your-very-secret-key-that-is-long-enough"
  duration_minutes: 60
