server:
  port: ":8080" # 网关的端口

services:
  - name: "auth-service"
    instances:
      - url: "http://localhost:8085"
        weight: 1
      - url: "http://localhost:8086"
        weight: 1
    health_check_path: "/healthz" # 健康检查端点
    load_balancer: "round_robin"  # 负载均衡策略: round_robin, weighted_round_robin, least_connections
  - name: "service-a"
    instances:
      - url: "http://localhost:8081"
        weight: 1
      - url: "http://localhost:8082"
        weight: 1
    health_check_path: "/healthz"
    load_balancer: "weighted_round_robin"  # 使用加权轮询
  - name: "service-b"
    instances:
      - url: "http://localhost:8083"
        weight: 1
      - url: "http://localhost:8084"
        weight: 1
    health_check_path: "/healthz"
    load_balancer: "least_connections"    # 使用最少连接数

routes:
  # 访问 /auth 开头的路径，转发给 auth-service，并且不需要 JWT 验证
  - path_prefix: "/auth"
    service_name: "auth-service"
    auth_required: false
  # 访问 /service-a 开头的路径，转发给 service-a，并且必须进行 JWT 验证
  - path_prefix: "/service-a"
    service_name: "service-a"
    auth_required: false
  # 示例：你也可以添加 service-b 的路由
  - path_prefix: "/service-b"
    service_name: "service-b"
    auth_required: true

jwt:
  # 这个密钥必须和认证服务里的完全一样
  secret_key: "your-very-secret-key-that-is-long-enough"
  duration_minutes: 60
